package main

// Glob intersection for IAM StringLike patterns.
//
// A per-project GitHub Actions role is fenced off from every other project by
// exactly one thing: the sub condition on its trust policy. Two projects in one
// AWS account whose subject lists overlap can each assume the other's role, and
// AWS says nothing about it — both applies succeed. To detect that we have to
// answer "does any string match both of these patterns", which is not string
// equality: repo:acme/api:* and repo:acme/api:ref:refs/heads/main overlap
// completely, and an exact comparison would report nothing.
//
// The semantics are IAM's, not the shell's or filepath.Match's:
//
//   - '*' is zero or more of any byte
//   - '?' is exactly one byte
//   - there is no escape character
//   - matching is case sensitive
//   - there is NO delimiter anchoring: '*' crosses ':' and '/' freely
//
// That last point is why repo:MadAppGang/* — the subject list this repository
// shipped as its default, until it was replaced by a placeholder — matches every
// repository, branch and pull request in the organisation, and why two meroku
// projects in one account used to overlap by default rather than by accident.
// path.Match and filepath.Match both stop '*' at a separator, so neither can be
// used here.
//
// Everything below works on []byte. sub claims are ASCII and IAM matches bytes,
// so indexing runes would make '?' match a multi-byte character as one, which
// is a different (and wrong) answer for the length-rigidity cases.

// globsIntersect reports whether any string matches both patterns.
//
// This is the recurrence from ai-docs/sessions/dev-feature-oidc-overlap-20260901,
// verified exhaustively against brute force by research/dp_verification.py over
// every pair of patterns of length <= 4 on {a,b,:,*,?}. It is transcribed
// literally on purpose — the interesting cases (crossing wildcards, '?' facing
// '*') are exactly the ones an "obvious improvement" gets wrong.
func globsIntersect(a, b []byte) bool {
	t := buildGlobTable(a, b)
	return t.at(0, 0)
}

// globWitness returns a concrete string that matches both patterns. ok is false
// when they do not intersect.
//
// The witness is what turns "these two roles might overlap" into "a token
// carrying this exact sub claim assumes both roles". It is reconstructed in a
// second pass over the already-filled table, never by re-running the search.
func globWitness(a, b []byte) (witness []byte, ok bool) {
	t := buildGlobTable(a, b)
	if !t.at(0, 0) {
		return nil, false
	}
	return t.walk(), true
}

// globWitnessFiller is emitted wherever both patterns accept any byte. Any byte
// would do; a readable one keeps the reported witness legible in a warning.
const globWitnessFiller = 'a'

// globMatch reports whether s matches pattern p.
//
// Deliberately written independently of the DP above, as the standard iterative
// matcher with star backtracking. Its purpose is to be an oracle: the tests
// check every witness the DP produces with this, so a shared bug in the
// recurrence cannot certify its own output.
func globMatch(p, s []byte) bool {
	m, n := len(p), len(s)
	i, j := 0, 0
	star := -1 // index in p of the most recent '*', -1 if none seen
	mark := 0  // index in s that star was first asked to absorb
	for j < n {
		switch {
		case i < m && (p[i] == '?' || p[i] == s[j]):
			i++
			j++
		case i < m && p[i] == '*':
			star = i
			mark = j
			i++
		case star != -1:
			// Backtrack: hand one more byte to the last star and retry.
			i = star + 1
			mark++
			j = mark
		default:
			return false
		}
	}
	// s is consumed; the pattern may only have trailing stars left.
	for i < m && p[i] == '*' {
		i++
	}
	return i == m
}

// globTable is the filled intersection table for one pair of patterns.
//
// cells[i*(n+1)+j] is f(i,j), "some string is generated by both a[i:] and
// b[j:]". Filling it bottom-up rather than recursing is the memoisation the
// architecture calls for: the naive recursion is exponential, and two
// star-dense 1024-byte patterns — well within what a sub claim can be — never
// return. Bottom-up also means the table is complete before the witness pass
// walks it, so reconstruction is a plain O(m+n) walk with no re-entry.
type globTable struct {
	a, b  []byte
	m, n  int
	cells []bool
}

func (t *globTable) at(i, j int) bool { return t.cells[i*(t.n+1)+j] }

// buildGlobTable collapses star runs and fills the O(m*n) table.
func buildGlobTable(a, b []byte) *globTable {
	// '**' matches exactly what '*' matches, so collapsing runs shrinks the
	// table for free. Note that '?*' and '*?' do NOT collapse: '*' matches the
	// empty string and neither of those can, and folding them together would
	// make every pattern requiring at least one byte look like it accepts none.
	a = collapseGlobStars(a)
	b = collapseGlobStars(b)

	t := &globTable{a: a, b: b, m: len(a), n: len(b)}
	t.cells = make([]bool, (t.m+1)*(t.n+1))

	// allStars suffix flags, needed by the two edge base cases: once one
	// pattern is exhausted the other can only agree by matching the empty
	// string, which only a run of stars does.
	aStars := allStarSuffixes(a)
	bStars := allStarSuffixes(b)

	// i and j descend so that every cell the recurrence reads — (i+1,j),
	// (i,j+1), (i+1,j+1) — is already written.
	for i := t.m; i >= 0; i-- {
		for j := t.n; j >= 0; j-- {
			var r bool
			switch {
			case i == t.m && j == t.n:
				r = true
			case i == t.m:
				r = bStars[j]
			case j == t.n:
				r = aStars[i]
			case a[i] == '*':
				r = t.at(i+1, j) || t.at(i, j+1)
			case b[j] == '*':
				r = t.at(i, j+1) || t.at(i+1, j)
			default:
				r = globBytesAgree(a[i], b[j]) && t.at(i+1, j+1)
			}
			t.cells[i*(t.n+1)+j] = r
		}
	}
	return t
}

// walk reconstructs one witness from the filled table.
//
// It replays the same case split the fill used, taking whichever branch the
// table says is true and emitting the byte that branch consumes. Every step
// increases i+j by exactly one, so it terminates in at most m+n steps on every
// input — including two patterns that are both "*", where no step emits
// anything and the witness is correctly the empty string.
//
// Precondition: at(0,0) is true.
func (t *globTable) walk() []byte {
	out := make([]byte, 0, t.m+t.n)
	i, j := 0, 0
	for {
		switch {
		case i == t.m || j == t.n:
			// Whatever is left of the other pattern is all stars (that is what
			// made this cell true), and stars match the empty string.
			return out

		case t.a[i] == '*':
			if t.at(i+1, j) {
				// The star takes nothing more; step past it.
				i++
				continue
			}
			// The star absorbs whatever b[j] produces.
			out = appendGlobByte(out, t.b[j])
			j++

		case t.b[j] == '*':
			if t.at(i, j+1) {
				j++
				continue
			}
			out = appendGlobByte(out, t.a[i])
			i++

		default:
			// Both are literals or '?', and they agree.
			switch {
			case t.a[i] != '?':
				out = append(out, t.a[i])
			case t.b[j] != '?':
				out = append(out, t.b[j])
			default:
				out = append(out, globWitnessFiller)
			}
			i++
			j++
		}
	}
}

// appendGlobByte emits the single byte a non-star pattern element consumes. A
// '*' consumes nothing here: it is the other pattern's star that has already
// been chosen to absorb this position, and a star may absorb zero bytes.
func appendGlobByte(out []byte, c byte) []byte {
	switch c {
	case '*':
		return out
	case '?':
		return append(out, globWitnessFiller)
	default:
		return append(out, c)
	}
}

// globBytesAgree reports whether two non-star pattern bytes can consume the
// same input byte.
func globBytesAgree(x, y byte) bool {
	return x == '?' || y == '?' || x == y
}

// collapseGlobStars rewrites runs of '*' as a single '*'. The returned slice
// aliases p when there is nothing to collapse, so callers must not mutate it.
func collapseGlobStars(p []byte) []byte {
	run := false
	doubled := false
	for _, c := range p {
		if c == '*' && run {
			doubled = true
			break
		}
		run = c == '*'
	}
	if !doubled {
		return p
	}
	out := make([]byte, 0, len(p))
	for _, c := range p {
		if c == '*' && len(out) > 0 && out[len(out)-1] == '*' {
			continue
		}
		out = append(out, c)
	}
	return out
}

// allStarSuffixes[i] reports whether p[i:] consists only of '*'.
func allStarSuffixes(p []byte) []bool {
	out := make([]bool, len(p)+1)
	out[len(p)] = true
	for i := len(p) - 1; i >= 0; i-- {
		out[i] = p[i] == '*' && out[i+1]
	}
	return out
}
